name: oceanprotocol
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

dependencies:
  http: ^1.1.2
  args: ^2.4.2
  path:
  ecdsa:
  logger:
  encrypt: ^5.0.3
  cryptography: ^2.7.0
  crypto:
  web3dart:
  pointycastle:
  json_annotation: ^4.5.0
  freezed_annotation:

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  build_runner:
  json_serializable: 6.7.1
  freezed:
